name: Hello World Worflow

on: 
    push:
        branches: [ "Brakissa-Sophia" ]

jobs: 
    hello-world-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Say hello
          run: echo "Hello, World !"