name: Hello World Workflow

on:
  push:
    branches: ["jessica"]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello, World!"
